 genus.tips=c("Anacheilium",
 "Andinia"           ,
 "Barbosella"       ,
 "Brachtia"          ,    
 "Cranichis"      ,
 "Cyclopogon"      ,      
 "Cyrtochilum"     ,
 "Dracula"          ,   
 "Elleanthus"   ,
 "Epidendrum",
 "Erythrodes" ,           
 "Fernandezia" ,          
 "Govenia"      ,     
 "Habenaria"     , 
 "Ida"            ,  
 "Lepanthes"      ,
 "Maxillaria"     ,
 "Odontoglossum"   ,  
 "Oncidium"      ,
 "Pachyphyllum" ,
 "Pleurothallis" ,  
 "Prescottia"    ,
 "Pseudocentrum"  ,
 "Sauroglossum"    ,  
 "Sobralia"       ,
 "Stelis"          ,
 "Telipogon"        ,  
 "Trichosalpinx" ,
 "Xylobium"    ,
 "Arabidopsis"  ,      
 "Liparis"       , 
 "Malaxis")
 